### ISSUE TITLE
Add support for specific images

### ISSUE THREAD

**Issue by untouchable** [BohemianCoding/unsplash-sketchplugin#11]
**Problem Description**
Currently it takes longer than expected to find suitable photos for a design as the results are sometimes too random to meet specific design requirements. Also, search terms longer than a couple of words result in a network connection error which leads to making broad searches that end up compounding the problem.

**Suggested Solution**
1. Find photo on unsplash.com with a browser, and switch to Sketch;
2. Select a symbol or layer to add or refresh data feed photo;
3. Open 'Search Photo...' window, paste photo url, and hit return;
4. See the expected image show up in selected layer or symbol.

**Additional Info**
- Sketch 52.6 (67491)
- Unsplash Plugin v1.0.3
- MacOS 10.14.1

**Comment by patrickdaze** [comment]
Hi @untouchable, I think [my pull request](https://github.com/BohemianCoding/unsplash-sketchplugin/pull/10) might be similar to what you're searching.

**Comment by bomberstudios** [comment]
Sorry about that, I totally missed your PR! I'll review and merge it ASAP

**Comment by bomberstudios** [comment]
@untouchable you said:

> search terms longer than a couple of words result in a network connection error

can you please provide an example of this issue?

**Comment by bomberstudios** [comment]
@patrickdaze's PR was just merged, and will be part of the next release of the plugin.

Thanks Patrick!
